-- Generated by scripts/export_architecture_artifacts.py
-- Target: MySQL 8.x, utf8mb4.

CREATE DATABASE IF NOT EXISTS job_kg DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE job_kg;

CREATE TABLE IF NOT EXISTS job_postings (
  record_id VARCHAR(255) PRIMARY KEY,
  origin_record_id VARCHAR(255),
  source_id VARCHAR(128),
  source_type VARCHAR(128),
  source_name VARCHAR(255),
  source_url TEXT,
  collected_at VARCHAR(64),
  published_at VARCHAR(64),
  country VARCHAR(128),
  province VARCHAR(128),
  city VARCHAR(255),
  company VARCHAR(255),
  department VARCHAR(255),
  product VARCHAR(255),
  category VARCHAR(255),
  normalized_category VARCHAR(128),
  job_title VARCHAR(512),
  job_type VARCHAR(128),
  work_years VARCHAR(128),
  responsibility MEDIUMTEXT,
  requirement MEDIUMTEXT,
  raw_text MEDIUMTEXT,
  normalized_skills TEXT,
  skill_count INT,
  quality_score INT,
  quality_level VARCHAR(8),
  quality_flags TEXT,
  content_hash VARCHAR(64),
  INDEX idx_job_source (source_id),
  INDEX idx_job_category (normalized_category),
  INDEX idx_job_city (city),
  INDEX idx_job_quality (quality_level)
);

CREATE TABLE IF NOT EXISTS job_skill_evidence (
  record_id VARCHAR(255) PRIMARY KEY,
  job_record_id VARCHAR(255),
  source_id VARCHAR(128),
  source_name VARCHAR(255),
  skill VARCHAR(255),
  evidence MEDIUMTEXT,
  collected_at VARCHAR(64),
  INDEX idx_skill_job (job_record_id),
  INDEX idx_skill_name (skill)
);

CREATE TABLE IF NOT EXISTS kg_nodes (
  id VARCHAR(255) PRIMARY KEY,
  label VARCHAR(512),
  type VARCHAR(64),
  canonical VARCHAR(512),
  count INT,
  first_seen VARCHAR(16),
  last_seen VARCHAR(16),
  properties JSON,
  INDEX idx_node_type (type)
);

CREATE TABLE IF NOT EXISTS kg_edges (
  id VARCHAR(512) PRIMARY KEY,
  from_id VARCHAR(255),
  to_id VARCHAR(255),
  type VARCHAR(64),
  weight INT,
  confidence DECIMAL(5,2),
  first_seen VARCHAR(16),
  last_seen VARCHAR(16),
  evidence MEDIUMTEXT,
  INDEX idx_edge_from (from_id),
  INDEX idx_edge_to (to_id),
  INDEX idx_edge_type (type)
);

CREATE TABLE IF NOT EXISTS skill_trends (
  period VARCHAR(16),
  role_id VARCHAR(255),
  role VARCHAR(512),
  skill VARCHAR(255),
  dimension VARCHAR(255),
  demand INT,
  source_count INT,
  PRIMARY KEY (period, role_id, skill),
  INDEX idx_trend_skill (skill),
  INDEX idx_trend_role (role_id)
);

CREATE TABLE IF NOT EXISTS data_quality_report (
  source_id VARCHAR(128) PRIMARY KEY,
  source_name VARCHAR(255),
  source_type VARCHAR(128),
  records INT,
  avg_quality_score DECIMAL(6,2),
  level_a INT,
  level_b INT,
  level_c INT,
  level_d INT,
  missing_title INT,
  missing_source_url INT,
  missing_collected_at INT,
  missing_published_at INT,
  missing_city INT,
  missing_company INT,
  missing_origin_record_id INT,
  short_responsibility INT,
  short_requirement INT,
  no_skill_hit INT,
  duplicate_content INT,
  unknown_source INT
);
