// Generated by scripts/export_architecture_artifacts.py
// Copy data/kg/nodes.csv and data/kg/edges.csv into Neo4j import directory first.

CREATE CONSTRAINT kg_node_id IF NOT EXISTS FOR (n:KgNode) REQUIRE n.id IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///nodes.csv' AS row
MERGE (n:KgNode {id: row.id})
SET n.label = row.label,
    n.type = row.type,
    n.canonical = row.canonical,
    n.count = toInteger(row.count),
    n.firstSeen = row.first_seen,
    n.lastSeen = row.last_seen,
    n.propertiesJson = row.properties;

LOAD CSV WITH HEADERS FROM 'file:///edges.csv' AS row
MATCH (a:KgNode {id: row['from']})
MATCH (b:KgNode {id: row['to']})
MERGE (a)-[r:KG_RELATION {id: row.id}]->(b)
SET r.type = row.type,
    r.weight = toInteger(row.weight),
    r.confidence = toFloat(row.confidence),
    r.firstSeen = row.first_seen,
    r.lastSeen = row.last_seen,
    r.evidence = row.evidence;
