import csv
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
ETL_DIR = DATA_DIR / "etl"
KG_DIR = DATA_DIR / "kg"
WAREHOUSE_DIR = DATA_DIR / "warehouse"

UNIFIED_JOBS_PATH = ETL_DIR / "unified_jobs.csv"
UNIFIED_SKILLS_PATH = ETL_DIR / "unified_job_skills.csv"
QUALITY_PATH = ETL_DIR / "data_quality_report.csv"
NODES_PATH = KG_DIR / "nodes.csv"
EDGES_PATH = KG_DIR / "edges.csv"
TRENDS_PATH = KG_DIR / "skill_trends.csv"

MYSQL_SCHEMA_PATH = WAREHOUSE_DIR / "mysql_schema.sql"
MYSQL_LOAD_PATH = WAREHOUSE_DIR / "mysql_load.sql"
ES_NDJSON_PATH = WAREHOUSE_DIR / "elasticsearch_jobs.ndjson"
CHROMA_DOCS_PATH = WAREHOUSE_DIR / "chroma_documents.jsonl"
NEO4J_CYPHER_PATH = WAREHOUSE_DIR / "neo4j_import.cypher"
MANIFEST_PATH = WAREHOUSE_DIR / "architecture_manifest.json"


def now_iso():
    return datetime.now(timezone(timedelta(hours=8))).isoformat(timespec="seconds")


def read_csv(path):
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def rel(path):
    return path.relative_to(ROOT).as_posix()


def write_text(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def text_for_embedding(row):
    parts = [
        row.get("job_title", ""),
        row.get("company", ""),
        row.get("normalized_category", ""),
        row.get("city", ""),
        row.get("responsibility", ""),
        row.get("requirement", ""),
        row.get("normalized_skills", ""),
    ]
    return "\n".join(str(part).strip() for part in parts if str(part).strip())


def build_mysql_schema():
    return """-- Generated by scripts/export_architecture_artifacts.py
-- Target: MySQL 8.x, utf8mb4.

CREATE DATABASE IF NOT EXISTS job_kg DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE job_kg;

CREATE TABLE IF NOT EXISTS job_postings (
  record_id VARCHAR(255) PRIMARY KEY,
  origin_record_id VARCHAR(255),
  source_id VARCHAR(128),
  source_type VARCHAR(128),
  source_name VARCHAR(255),
  source_url TEXT,
  collected_at VARCHAR(64),
  published_at VARCHAR(64),
  country VARCHAR(128),
  province VARCHAR(128),
  city VARCHAR(255),
  company VARCHAR(255),
  department VARCHAR(255),
  product VARCHAR(255),
  category VARCHAR(255),
  normalized_category VARCHAR(128),
  job_title VARCHAR(512),
  job_type VARCHAR(128),
  work_years VARCHAR(128),
  responsibility MEDIUMTEXT,
  requirement MEDIUMTEXT,
  raw_text MEDIUMTEXT,
  normalized_skills TEXT,
  skill_count INT,
  quality_score INT,
  quality_level VARCHAR(8),
  quality_flags TEXT,
  content_hash VARCHAR(64),
  INDEX idx_job_source (source_id),
  INDEX idx_job_category (normalized_category),
  INDEX idx_job_city (city),
  INDEX idx_job_quality (quality_level)
);

CREATE TABLE IF NOT EXISTS job_skill_evidence (
  record_id VARCHAR(255) PRIMARY KEY,
  job_record_id VARCHAR(255),
  source_id VARCHAR(128),
  source_name VARCHAR(255),
  skill VARCHAR(255),
  evidence MEDIUMTEXT,
  collected_at VARCHAR(64),
  INDEX idx_skill_job (job_record_id),
  INDEX idx_skill_name (skill)
);

CREATE TABLE IF NOT EXISTS kg_nodes (
  id VARCHAR(255) PRIMARY KEY,
  label VARCHAR(512),
  type VARCHAR(64),
  canonical VARCHAR(512),
  count INT,
  first_seen VARCHAR(16),
  last_seen VARCHAR(16),
  properties JSON,
  INDEX idx_node_type (type)
);

CREATE TABLE IF NOT EXISTS kg_edges (
  id VARCHAR(512) PRIMARY KEY,
  from_id VARCHAR(255),
  to_id VARCHAR(255),
  type VARCHAR(64),
  weight INT,
  confidence DECIMAL(5,2),
  first_seen VARCHAR(16),
  last_seen VARCHAR(16),
  evidence MEDIUMTEXT,
  INDEX idx_edge_from (from_id),
  INDEX idx_edge_to (to_id),
  INDEX idx_edge_type (type)
);

CREATE TABLE IF NOT EXISTS skill_trends (
  period VARCHAR(16),
  role_id VARCHAR(255),
  role VARCHAR(512),
  skill VARCHAR(255),
  dimension VARCHAR(255),
  demand INT,
  source_count INT,
  PRIMARY KEY (period, role_id, skill),
  INDEX idx_trend_skill (skill),
  INDEX idx_trend_role (role_id)
);

CREATE TABLE IF NOT EXISTS data_quality_report (
  source_id VARCHAR(128) PRIMARY KEY,
  source_name VARCHAR(255),
  source_type VARCHAR(128),
  records INT,
  avg_quality_score DECIMAL(6,2),
  level_a INT,
  level_b INT,
  level_c INT,
  level_d INT,
  missing_title INT,
  missing_source_url INT,
  missing_collected_at INT,
  missing_published_at INT,
  missing_city INT,
  missing_company INT,
  missing_origin_record_id INT,
  short_responsibility INT,
  short_requirement INT,
  no_skill_hit INT,
  duplicate_content INT,
  unknown_source INT
);
"""


def build_mysql_load():
    return f"""-- Put this project directory on the MySQL client machine before running.
-- MySQL may require: SET GLOBAL local_infile = 1;

USE job_kg;

LOAD DATA LOCAL INFILE '{rel(UNIFIED_JOBS_PATH)}'
INTO TABLE job_postings
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '{rel(UNIFIED_SKILLS_PATH)}'
INTO TABLE job_skill_evidence
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '{rel(NODES_PATH)}'
INTO TABLE kg_nodes
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '{rel(EDGES_PATH)}'
INTO TABLE kg_edges
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES
(id, from_id, to_id, type, weight, confidence, first_seen, last_seen, evidence);

LOAD DATA LOCAL INFILE '{rel(TRENDS_PATH)}'
INTO TABLE skill_trends
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '{rel(QUALITY_PATH)}'
INTO TABLE data_quality_report
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;
"""


def export_elasticsearch(jobs):
    ES_NDJSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with ES_NDJSON_PATH.open("w", encoding="utf-8") as file:
        for row in jobs:
            record_id = row.get("record_id", "")
            doc = {
                "record_id": record_id,
                "title": row.get("job_title", ""),
                "company": row.get("company", ""),
                "city": row.get("city", ""),
                "country": row.get("country", ""),
                "source_id": row.get("source_id", ""),
                "source_name": row.get("source_name", ""),
                "source_type": row.get("source_type", ""),
                "source_url": row.get("source_url", ""),
                "published_at": row.get("published_at", ""),
                "collected_at": row.get("collected_at", ""),
                "normalized_category": row.get("normalized_category", ""),
                "skills": [item for item in row.get("normalized_skills", "").split("|") if item],
                "quality_score": int(row.get("quality_score") or 0),
                "quality_level": row.get("quality_level", ""),
                "text": text_for_embedding(row),
            }
            file.write(json.dumps({"index": {"_index": "job_postings", "_id": record_id}}, ensure_ascii=False) + "\n")
            file.write(json.dumps(doc, ensure_ascii=False) + "\n")


def export_chroma_documents(jobs):
    CHROMA_DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CHROMA_DOCS_PATH.open("w", encoding="utf-8") as file:
        for row in jobs:
            payload = {
                "id": row.get("record_id", ""),
                "document": text_for_embedding(row),
                "metadata": {
                    "source_id": row.get("source_id", ""),
                    "source_name": row.get("source_name", ""),
                    "source_url": row.get("source_url", ""),
                    "job_title": row.get("job_title", ""),
                    "company": row.get("company", ""),
                    "city": row.get("city", ""),
                    "country": row.get("country", ""),
                    "normalized_category": row.get("normalized_category", ""),
                    "published_at": row.get("published_at", ""),
                    "quality_score": int(row.get("quality_score") or 0),
                    "quality_level": row.get("quality_level", ""),
                },
            }
            file.write(json.dumps(payload, ensure_ascii=False) + "\n")


def build_neo4j_cypher():
    return """// Generated by scripts/export_architecture_artifacts.py
// Copy data/kg/nodes.csv and data/kg/edges.csv into Neo4j import directory first.

CREATE CONSTRAINT kg_node_id IF NOT EXISTS FOR (n:KgNode) REQUIRE n.id IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///nodes.csv' AS row
MERGE (n:KgNode {id: row.id})
SET n.label = row.label,
    n.type = row.type,
    n.canonical = row.canonical,
    n.count = toInteger(row.count),
    n.firstSeen = row.first_seen,
    n.lastSeen = row.last_seen,
    n.propertiesJson = row.properties;

LOAD CSV WITH HEADERS FROM 'file:///edges.csv' AS row
MATCH (a:KgNode {id: row['from']})
MATCH (b:KgNode {id: row['to']})
MERGE (a)-[r:KG_RELATION {id: row.id}]->(b)
SET r.type = row.type,
    r.weight = toInteger(row.weight),
    r.confidence = toFloat(row.confidence),
    r.firstSeen = row.first_seen,
    r.lastSeen = row.last_seen,
    r.evidence = row.evidence;
"""


def build():
    jobs = read_csv(UNIFIED_JOBS_PATH)
    skills = read_csv(UNIFIED_SKILLS_PATH)
    nodes = read_csv(NODES_PATH)
    edges = read_csv(EDGES_PATH)
    trends = read_csv(TRENDS_PATH)
    quality = read_csv(QUALITY_PATH)

    WAREHOUSE_DIR.mkdir(parents=True, exist_ok=True)
    write_text(MYSQL_SCHEMA_PATH, build_mysql_schema())
    write_text(MYSQL_LOAD_PATH, build_mysql_load())
    export_elasticsearch(jobs)
    export_chroma_documents(jobs)
    write_text(NEO4J_CYPHER_PATH, build_neo4j_cypher())

    manifest = {
        "generated_at": now_iso(),
        "inputs": {
            "unified_jobs": rel(UNIFIED_JOBS_PATH),
            "unified_skills": rel(UNIFIED_SKILLS_PATH),
            "kg_nodes": rel(NODES_PATH),
            "kg_edges": rel(EDGES_PATH),
            "skill_trends": rel(TRENDS_PATH),
            "quality_report": rel(QUALITY_PATH),
        },
        "counts": {
            "jobs": len(jobs),
            "skill_evidence": len(skills),
            "kg_nodes": len(nodes),
            "kg_edges": len(edges),
            "skill_trends": len(trends),
            "quality_sources": len(quality),
        },
        "outputs": {
            "mysql_schema": rel(MYSQL_SCHEMA_PATH),
            "mysql_load": rel(MYSQL_LOAD_PATH),
            "elasticsearch_ndjson": rel(ES_NDJSON_PATH),
            "chroma_documents": rel(CHROMA_DOCS_PATH),
            "neo4j_cypher": rel(NEO4J_CYPHER_PATH),
        },
        "notes": [
            "CSV remains the local source of truth for the prototype.",
            "MySQL, Elasticsearch, Neo4j and ChromaDB artifacts are generated for production migration.",
            "Neo4j import uses a generic KG_RELATION type and stores the semantic relation in r.type.",
        ],
    }
    write_json(MANIFEST_PATH, manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    build()
